server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///rxb
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.rao.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.rao: debug